export default {
	GET_DRIVER_LOCATION:'GET_DRIVER_LOCATION',
	GET_USER_DATA:'GET_USER_DATA',
	GET_USER_ACCOUNTS:'GET_USER_ACCOUNTS',
	GET_USER_JOBS:'GET_USER_JOBS',
	GET_ALL_JOBS:'GET_ALL_JOBS',
	DRIVER_BIDS: 'DRIVER_BIDS',
	UPDATE_BIDS: 'UPDATE_BIDS'
};